"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { getCircleCatalog } from "./circle-records";
import { PUBLISHED_EVENTS } from "./event-catalog";
import type { EventDayKey, PlanningDocument } from "./planning-store";
import { addSharedToPlan, projectSharedItinerary, resolveSharedList, SHARE_MAX_ITEMS, type ShareSnapshot } from "./planning-share";
import { createShortLink, readShortLink } from "./planning-share-client";
import { sharePublicContent } from "./public-share";
import { useCircleCatalog } from "./use-circle-catalog";
import { useModalFocus } from "./use-modal-focus";
import { UiIcon } from "./ui-icons";
import styles from "./planning-tools.module.css";

/** Read once, before the reader rebuilds its URL from its own whitelist (ADR-0079). */
const initialShareId = typeof window === "undefined" ? null : new URLSearchParams(window.location.search).get("share");
/** Closed once means consumed: switching between map and browse remounts the dialog. */
let shareDismissed = false;

const eventOf = (eventId: string) => PUBLISHED_EVENTS.find((event) => event.id === eventId);
function dayLabel(eventId: string, day: EventDayKey) {
  const found = eventOf(eventId)?.days.find((item) => String(item.id) === String(day));
  return found ? `${found.label}（${found.dateLabel}）` : `DAY ${day}`;
}
const itemKey = (item: { circleId: string; day: EventDayKey }) => `${item.circleId}\u0000${item.day}`;

function Dialog({ title, labelId, onClose, children }: { title: string; labelId: string; onClose: () => void; children: ReactNode }) {
  const ref = useRef<HTMLElement | null>(null);
  useModalFocus(true, ref, onClose);
  return createPortal(<div className={styles.backdrop} role="presentation" onPointerDown={(pressed) => { if (pressed.target === pressed.currentTarget) onClose(); }}>
    <section ref={ref} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby={labelId} tabIndex={-1}>
      <header><div><h2 id={labelId}>{title}</h2></div><button onClick={onClose} aria-label={`關閉${title}`}><UiIcon name="close" /></button></header>
      {children}
    </section>
  </div>, document.body);
}

/** The short link as a QR code drawn in the browser; the QR module loads only once a link exists. */
function ShortLinkQr({ url }: { url: string }) {
  const [svg, setSvg] = useState("");
  useEffect(() => {
    let active = true;
    void import("qrcode-generator").then(({ default: qrcode }) => {
      const qr = qrcode(0, "M");
      qr.addData(url);
      qr.make();
      if (active) setSvg(qr.createSvgTag({ cellSize: 4, margin: 2, scalable: true }));
    }).catch(() => { if (active) setSvg(""); });
    return () => { active = false; };
  }, [url]);
  // Markup generated by the QR library for our own short URL, never user input.
  return svg ? <div className={styles.shareQr} role="img" aria-label="短網址 QR Code" dangerouslySetInnerHTML={{ __html: svg }} /> : null;
}

/** 分享行程: pick itinerary items of this event, create a short link, copy / share / show its QR code. */
export function ShareItineraryDialog({ eventId, document, onClose }: { eventId: string; document: PlanningDocument; onClose: () => void }) {
  const catalog = getCircleCatalog(eventId);
  const name = (circleId: string) => {
    const record = catalog.recordsByCircleId.get(circleId)?.[0];
    return record ? `${record.placement.boothCode} ${record.circle.name}` : circleId;
  };
  const candidates = document.visitPlans.filter((entry) => entry.eventId === eventId)
    .map((entry) => ({ circleId: entry.circleId, day: entry.day, label: `${dayLabel(eventId, entry.day)} · ${name(entry.circleId)}` }));
  const [unchecked, setUnchecked] = useState<Set<string>>(() => new Set());
  const [state, setState] = useState<{ kind: "idle" } | { kind: "creating" } | { kind: "ready"; url: string } | { kind: "error"; message: string }>({ kind: "idle" });
  const [message, setMessage] = useState("");
  const selected = candidates.filter((item) => !unchecked.has(itemKey(item)));

  function toggle(key: string) {
    setState({ kind: "idle" }); setMessage("");
    setUnchecked((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; });
  }
  async function create() {
    setState({ kind: "creating" });
    const snapshot = projectSharedItinerary(document, eventId, selected.map(({ circleId, day }) => ({ circleId, day })));
    const result = await createShortLink(snapshot);
    setState(result.ok ? { kind: "ready", url: result.url } : { kind: "error", message: result.error });
  }
  async function share(url: string) {
    const result = await sharePublicContent({ title: `${eventOf(eventId)?.name ?? eventId} 逛攤清單`, url });
    setMessage(result === "copied" ? "已複製連結。" : result === "manual" ? "請手動複製上方連結。" : "");
  }

  return <Dialog title="分享行程" labelId="share-itinerary-title" onClose={onClose}>
    <section className={styles.section}>
      <div><p>建立短網址，傳到自己的手機或分享給朋友。只包含攤位與日期，不含備註、群組、購買項目與預算；連結可被轉傳，活動結束 30 天後失效。</p></div>
      {candidates.length === 0 ? <p>這場活動還沒有行程可以分享。</p> : <>
        <fieldset className={styles.sharePick}>
          <legend>將分享 {selected.length} 個</legend>
          {/* Locked while creating, so the link always matches what is ticked. */}
          {candidates.map((item) => <label key={itemKey(item)}><input type="checkbox" disabled={state.kind === "creating"} checked={!unchecked.has(itemKey(item))} onChange={() => toggle(itemKey(item))} />{item.label}</label>)}
        </fieldset>
        {selected.length > SHARE_MAX_ITEMS && <p className={styles.errorText}>一次最多分享 {SHARE_MAX_ITEMS} 個，請取消勾選 {selected.length - SHARE_MAX_ITEMS} 個。</p>}
        {state.kind !== "ready" && <div className={styles.confirmActions}>
          <button className={styles.primary} disabled={state.kind === "creating" || selected.length === 0 || selected.length > SHARE_MAX_ITEMS} onClick={() => void create()}>{state.kind === "creating" ? "建立中…" : "建立短網址"}</button>
        </div>}
        {state.kind === "error" && <p className={styles.errorText} role="alert">{state.message}</p>}
        {state.kind === "ready" && <div className={styles.shareResult}>
          <div className={styles.shareLink}>
            <input readOnly aria-label="短網址" value={state.url} onFocus={(focused) => focused.currentTarget.select()} />
            <button onClick={() => void share(state.url)}>複製或分享</button>
          </div>
          <ShortLinkQr url={state.url} />
          {message && <p className={styles.okText} role="status">{message}</p>}
        </div>}
      </>}
    </section>
  </Dialog>;
}

type Opened =
  | { kind: "loading" }
  | { kind: "ok"; snapshot: ShareSnapshot }
  | { kind: "expired"; eventId: string | null }
  | { kind: "missing" }
  | { kind: "error"; error: string };

/** A short link opened in the reader (`?share=<id>`): read-only until 加入我的行程 (#415, ADR-0079). */
export function SharedItineraryDialog({ eventId, update, blocked }: {
  eventId: string;
  update: (change: (current: PlanningDocument) => PlanningDocument) => void;
  blocked: boolean;
}) {
  const [shareId, setShareId] = useState(() => (shareDismissed ? null : initialShareId));
  const [opened, setOpened] = useState<Opened>({ kind: "loading" });
  useEffect(() => {
    if (!shareId) return;
    let active = true;
    void readShortLink(shareId).then((result) => {
      if (active) setOpened(result.kind === "ok" ? { kind: "ok", snapshot: result.snapshot } : result);
    });
    return () => { active = false; };
  }, [shareId]);
  if (!shareId) return null;
  const close = () => {
    shareDismissed = true;
    setShareId(null);
    const url = new URL(window.location.href);
    url.searchParams.delete("share");
    window.history.replaceState(window.history.state, "", url);
  };
  const expiredEvent = opened.kind === "expired" && opened.eventId ? eventOf(opened.eventId) : undefined;
  return <Dialog title="分享的行程" labelId="shared-itinerary-title" onClose={close}>
    {opened.kind === "loading" && <p className={styles.notice} role="status">正在讀取分享的行程…</p>}
    {opened.kind === "missing" && <div className={styles.section}><p>這個分享連結不存在或已過期。</p><a className={styles.linkButton} href="/">查看場刊 Map 的活動</a></div>}
    {opened.kind === "expired" && <div className={styles.section}><p>這個分享連結已過期。</p>{expiredEvent && <a className={styles.linkButton} href={`/?event=${encodeURIComponent(expiredEvent.id)}`}>查看 {expiredEvent.name}</a>}</div>}
    {opened.kind === "error" && <p className={styles.errorText} role="alert">{opened.error}</p>}
    {opened.kind === "ok" && <SharedItineraryBody snapshot={opened.snapshot} shareId={shareId} eventId={eventId} update={update} blocked={blocked} onAdded={close} />}
  </Dialog>;
}

function SharedItineraryBody({ snapshot, shareId, eventId, update, blocked, onAdded }: {
  snapshot: ShareSnapshot; shareId: string; eventId: string;
  update: (change: (current: PlanningDocument) => PlanningDocument) => void; blocked: boolean;
  /** Closes the preview once added; the 行程 count is the confirmation. */
  onAdded: () => void;
}) {
  // Re-render when the event's catalog arrives, so items are not judged against an empty one.
  useCircleCatalog(snapshot.eventId);
  const event = eventOf(snapshot.eventId);
  const resolved = resolveSharedList(snapshot);
  if (!event) return <p className={styles.errorText} role="alert">這份行程的活動目前沒有公開。</p>;
  if (snapshot.eventId !== eventId) return <div className={styles.section}><p>這份行程是「{event.name}」的攤位。</p>
    <a className={styles.linkButton} href={`/?event=${encodeURIComponent(snapshot.eventId)}&share=${encodeURIComponent(shareId)}`}>到 {event.name} 查看</a></div>;
  const available = resolved.items.filter((item) => item.state === "available").map(({ circleId, day }) => ({ circleId, day }));
  return <>
    <p className={styles.notice}>先看看再決定；按下加入前不會改動你的行程。</p>
    {resolved.status !== "ready" && <p className={styles.notice} role="status">{resolved.status === "loading" ? "正在讀取活動資料…" : "活動資料讀取失敗，暫時無法核對這份行程。"}</p>}
    <ol className={styles.sharedItems}>{resolved.items.map((item) => <li key={itemKey(item)}>
      <b>{item.records[0] ? `${item.records[0].placement.boothCode} ${item.circle?.name ?? ""}` : item.circleId}</b>
      <small>{item.state === "available" ? dayLabel(snapshot.eventId, item.day)
        : item.state === "moved" ? `已改到 ${item.days.map((value) => dayLabel(snapshot.eventId, value)).join("、")}，不會加入`
          : item.state === "withdrawn" ? "已取消參加，不會加入" : "目前找不到這個社團，不會加入"}</small>
    </li>)}</ol>
    {resolved.status === "ready" && <div className={styles.section}>
      <div className={styles.confirmActions}>
        <button className={styles.primary} disabled={blocked || available.length === 0} onClick={() => {
          update((current) => addSharedToPlan(current, snapshot.eventId, available).document);
          onAdded();
        }}>加入我的行程</button>
      </div>
      {blocked && <p className={styles.errorText}>這台裝置有無法讀取的舊資料，請先在「資料管理」處理。</p>}
    </div>}
  </>;
}
